version: '3.10'

services:

  app:
    build: ./api
    container_name: bwg_api
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    command: bash -c "
      cd src
      && uvicorn app:app --host 0.0.0.0 --port 8000
      "
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env.db
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  pg_data: