version: '3.10'

services:

  app:
    build: ./api
    container_name: bwg_api
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    command: bash -c "
      cd src
      && uvicorn app:app --host 0.0.0.0 --port 8000
      "
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: redis/redis-stack:7.2.0-v8
    expose:
      - 6379
    volumes:
      - redis_data:/data
    env_file:
      .env

  rabbitmq:
    image: rabbitmq:3.12.12-management
    hostname: rabbitmq
    ports:
      - 15672:15672
    volumes:
      - rmq_data:/var/lib/rabbitmq
    env_file:
      - .env

volumes:
  pg_data:
  redis_data:
  rmq_data: